version: '3.8'

services:
  db:
    image: postgres:15
    container_name: staffing_postgres
    environment:
      POSTGRES_USER: staffing_user
      POSTGRES_PASSWORD: staffing_pass
      POSTGRES_DB: staffing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
